// src/services/email.service.js
const nodemailer = require('nodemailer');
const logger = require('../config/logger');

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_SECURE === 'true',
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS
  }
});

const sendPasswordReset = async (toEmail, resetLink) => {
  const mailOptions = {
    from: process.env.EMAIL_FROM || 'no-reply@yourapp.com',
    to: toEmail,
    subject: '🔑 Password Reset Request',
    html: `
      <div style="font-family:Arial, sans-serif; background-color:#0f172a; color:#e2e8f0; padding:20px; border-radius:12px;">
        <h2 style="color:#3b82f6;">Password Reset Request</h2>
        <p>Hi there,</p>
        <p>We received a request to reset your password for <strong>${process.env.APP_NAME || 'DocuAI'}</strong>.</p>
        <p>Please click the button below to reset your password. This link is valid for <strong>1 hour</strong>.</p>
        <br>
        <a href="${resetLink}" 
          style="background-color:#3b82f6; color:#fff; text-decoration:none; padding:12px 20px; border-radius:8px; display:inline-block; font-weight:bold;">
          Reset My Password
        </a>
        <br><br>
        <p>If you did not request a password reset, you can safely ignore this email.</p>
        <br>
        <p style="font-size:12px; color:#94a3b8;">This email was sent by ${process.env.APP_NAME || 'DocuAI'}.</p>
      </div>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    logger.info(`Password reset email sent: ${info.messageId}`);
    return info;
  } catch (err) {
    logger.error('Error sending password reset email', err);
    throw err;
  }
};



const sendWelcomeEmail = async (toEmail, name) => {
  const mailOptions = {
    from: process.env.EMAIL_FROM || 'no-reply@yourapp.com',
    to: toEmail,
    subject: `🎉 Welcome to ${process.env.APP_NAME || 'DocuAI'}!`,
    html: `
      <div style="font-family:Arial, sans-serif; background-color:#0f172a; color:#e2e8f0; padding:20px; border-radius:12px;">
        <h2 style="color:#3b82f6;">Welcome, ${name}!</h2>
        <p>We’re thrilled to have you join <strong>${process.env.APP_NAME || 'DocuAI'}</strong>.</p>
        <p>Your account has been created successfully, and you can now log in to start exploring our features.</p>
        <br>
        <a href="${process.env.APP_URL || '#'}" 
          style="background-color:#3b82f6; color:#fff; text-decoration:none; padding:12px 20px; border-radius:8px; display:inline-block; font-weight:bold;">
          Get Started
        </a>
        <br><br>
        <p>If you have any questions, feel free to reach out to us anytime.</p>
        <p>Cheers,</p>
        <p>The ${process.env.APP_NAME || 'DocuAI'} Team</p>
        <br>
        <p style="font-size:12px; color:#94a3b8;">This is an automated email, please do not reply directly.</p>
      </div>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    logger.info(`Welcome email sent: ${info.messageId}`);
    return info;
  } catch (err) {
    logger.error('Error sending welcome email', err);
    throw err;
  }
};




const sendAdminContactEmail = async (name, email, message) => {
  const mailOptions = {
    from: process.env.EMAIL_FROM || 'no-reply@yourapp.com',
    to: process.env.ADMIN_EMAIL || 'msrizwi404.remote@gmail.com', // admin email set in .env
    subject: `📩 New Contact Form Submission from ${name}`,
    html: `
      <div style="font-family:Arial, sans-serif; background-color:#0f172a; color:#e2e8f0; padding:20px; border-radius:12px;">
        <h2 style="color:#3b82f6;">New Contact Form Submission</h2>
        <p><strong>Name:</strong> ${name}</p>
        <p><strong>Email:</strong> ${email}</p>
        <p><strong>Message:</strong></p>
        <blockquote style="border-left:4px solid #3b82f6; margin:10px 0; padding:10px; color:#cbd5e1;">
          ${message}
        </blockquote>
        <br>
        <p style="font-size:12px; color:#94a3b8;">This email was automatically generated by ${process.env.APP_NAME || 'DocuAI'}.</p>
      </div>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    logger.info(`Admin contact email sent: ${info.messageId}`);
    return info;
  } catch (err) {
    logger.error('Error sending admin contact email', err);
    throw err;
  }
};

// 2️⃣ Confirmation Mail to User
const sendUserConfirmationEmail = async (name,toEmail ) => {
  const mailOptions = {
    from: process.env.EMAIL_FROM || 'no-reply@yourapp.com',
    to: toEmail,
    subject: '✅ We Received Your Message',
    html: `
      <div style="font-family:Arial, sans-serif; background-color:#0f172a; color:#e2e8f0; padding:20px; border-radius:12px;">
        <h2 style="color:#3b82f6;">Thank You, ${name}!</h2>
        <p>We’ve received your message and our team will get back to you shortly.</p>
        <p>Meanwhile, feel free to explore more about <strong>${process.env.APP_NAME || 'DocuAI'}</strong>.</p>
        <br>
        <a href="${process.env.APP_URL || '#'}" style="background-color:#3b82f6; color:white; text-decoration:none; padding:10px 20px; border-radius:8px;">Visit Our Website</a>
        <br><br>
        <p style="font-size:12px; color:#94a3b8;">This is a confirmation email from ${process.env.APP_NAME || 'DocuAI'}.</p>
      </div>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    logger.info(`User confirmation email sent: ${info.messageId}`);
    return info;
  } catch (err) {
    logger.error('Error sending user confirmation email', err);
    throw err;
  }
};

module.exports = { sendPasswordReset,sendWelcomeEmail, sendAdminContactEmail, sendUserConfirmationEmail };
